!
! Zebra configuration saved from vty
!   2026/03/10 18:13:15
!
frr version 10.0.2_git
frr defaults traditional
!
hostname FRR-3
!
!
!
!
!
!
interface eth0
 ip address 10.0.0.1/30
exit
!
interface eth1
 ip address 10.1.0.1/30
exit
!
